include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: main
    file: '/test/auto.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: main
    file: '/build/docker/docker-build.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: main
    file: '/deploy/service/docker-deploy.yml'
  - local: '/.gitlab-ci/build.yml'
  - local: '/.gitlab-ci/test.yml'

.docker-deploy:
  variables:
    STACK: client
    DEPLOY_ENVIRONMENT_URL: https://${PUBLIC_HOSTNAME}
