include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/license-listing.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-custom-image.yml'

stages:
  - pre-build
  - build
  - license-list
  - pre-package
  - package
  - post-package
  - deploy
  - test-deploy

.web-build:
  image: ${WEB_BUILD_IMAGE_NAME}:${WEB_BUILD_IMAGE_TAG}
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    WEB_BUILD_IMAGE_NAME: registry.gitlab.com/redmic-project/docker/web-build
    WEB_BUILD_IMAGE_TAG: latest
  before_script:
    - type yarn grunt java
    - yarn install
    - grunt preBuild
  cache:
    paths:
      - node_modules/
      - public/javascript/redmic-widgets/node_modules/
      - public/javascript/templates/node_modules/
      - public/stylesheets/node_modules/

.only-non-master-branches-job:
  rules: &only-non-master-branches-job-rules
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_COMMIT_BRANCH == "master"
      when: never
    - if: $CI_COMMIT_BRANCH

prepare-unbuilt-version:
  extends: .web-build
  stage: pre-build
  script: ':'
  artifacts:
    name: ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}
    expire_in: 1 week
    paths:
      - node_modules/
      - public/javascript/proj4js/dist/proj4.js
      - public/javascript/redmic-widgets/src/app/
      - public/javascript/templates/dist/
      - public/stylesheets/style.styl
      - public/stylesheets/src/
      - public/stylesheets/submodules/
  rules: *only-non-master-branches-job-rules

.run-tests:
  extends: .web-build
  tags:
    - custom-runner
  cache:
    policy: pull

.run-pre-build-tests:
  extends: .run-tests
  stage: pre-build
  rules: *only-non-master-branches-job-rules
  allow_failure: true

.run-remote-tests:
  variables: &run-remote-test-variables
    TEST_REMOTE_HOST: selenium-hub

.run-remote-unit-tests:
  extends: .run-pre-build-tests
  variables:
    <<: *run-remote-test-variables
  script:
    - grunt test-unit-remote --headless --browser=${TEST_BROWSER} --remoteHost=${TEST_REMOTE_HOST} | tee test.out
    - coverage=$(grep '^All files.*' test.out | cut -d '|' -f 2 | tr -d ' ')
    - echo "Coverage - ${coverage}%"
    - rm test.out

run-remote-unit-tests-chrome:
  extends: .run-remote-unit-tests
  variables:
    TEST_BROWSER: chrome

run-remote-unit-tests-firefox:
  extends: .run-remote-unit-tests
  variables:
    TEST_BROWSER: firefox

.run-remote-modules-functional-tests:
  extends: .run-pre-build-tests
  variables:
    <<: *run-remote-test-variables
  script:
    - npm start &
    - >
      grunt test-functional-remote --functionalSuites=tests/functional/modules/**/!\(*Script\).js --headless
      --browser=${TEST_BROWSER} --remoteHost=${TEST_REMOTE_HOST}

run-remote-modules-functional-tests-chrome:
  extends: .run-remote-modules-functional-tests
  variables:
    TEST_BROWSER: chrome

run-remote-modules-functional-tests-firefox:
  extends: .run-remote-modules-functional-tests
  variables:
    TEST_BROWSER: firefox

prepare-built-version:
  extends: .web-build
  stage: build
  script:
    - grunt
  dependencies: []
  artifacts:
    name: ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}
    expire_in: 1 month
    paths:
      - dist*.tar.gz
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG

.deploy:
  variables:
    STACK: client
  environment:
    url: https://${PUBLIC_HOSTNAME}

run-scheduled-remote-functional-tests:
  extends: .run-tests
  stage: test-deploy
  variables:
    <<: *run-remote-test-variables
  script:
    - >
      grunt test-functional-local --serverUrl="https://${DEV_PUBLIC_HOSTNAME}" --user="${REDMIC_TEST_USER}"
      --pass="${REDMIC_TEST_PASS}" --role=administrator --suitesGroups="${SUITES_GROUPS}" --headless --browser=chrome
      --browser=firefox --remoteHost=${TEST_REMOTE_HOST}
  dependencies: []
  artifacts:
    name: ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}
    expire_in: 1 month
    when: always
    paths:
      - 'test_reports/test-functional-local*'
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
