include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/license-listing.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-custom-image.yml'
  - local: '/.gitlab-ci.build.yml'
  - local: '/.gitlab-ci.test.yml'

stages:
  - pre-build
  - build
  - license-list
  - pre-package
  - package
  - post-package
  - deploy
  - test-deploy

.deploy:
  variables:
    STACK: client
  environment:
    url: https://${PUBLIC_HOSTNAME}
