version: '3.5'

services:
  web:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    networks:
      - redmic-net
    environment:
      - OAUTH_URL
      - OAUTH_CLIENT_SECRET
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${WEB_PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  redmic-net:
    external: true
