version: '3.5'

services:
  web:
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${WEB_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: PathPrefix:/
        traefik.frontend.errors.50x.status: "502-504"
        traefik.frontend.errors.50x.backend: static-pages
        traefik.frontend.errors.50x.query: '/50x'
        traefik.backend: web
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 1m
        window: 3m

networks:
  traefik-net:
    external: true
