.web-build:
  image: ${WEB_BUILD_IMAGE_NAME}:${WEB_BUILD_IMAGE_TAG}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    WEB_BUILD_IMAGE_NAME: registry.gitlab.com/redmic-project/docker/web-build
    WEB_BUILD_IMAGE_TAG: latest
  before_script:
    - type npm
    - npm install
  cache:
    paths:
      - node_modules/
      - client-app/dep/templates/node_modules/
      - client-app/style/node_modules/

prepare-unbuilt-version:
  extends: .web-build
  stage: pre-build
  script:
    - npm -v
    - node -v
  dependencies: []
  tags:
    - custom-runner
  artifacts:
    name: ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}
    expire_in: 1 week
    paths:
      - node_modules/
      - package-lock.json
      - client-app/dep/templates/dist/
      - client-app/style/style.styl
      - client-app/style/src/
      - client-app/style/dep/
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_COMMIT_BRANCH == "master"
      when: never
    - if: $CI_COMMIT_BRANCH

prepare-built-version:
  extends: .web-build
  stage: build
  script:
    - npm pack
  dependencies: []
  artifacts:
    name: ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}
    expire_in: 1 month
    paths:
      - package-lock.json
      - redmic-project-web-*.tgz
      - client-app/build-report.txt
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
