services:
  web:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/client/web}:${IMAGE_TAG:-latest}
    environment:
      OAUTH_URL:
      OAUTH_CLIENT_ID:
      OAUTH_CLIENT_SECRET:
      API_URL:
      CONFIG_URL:
      SITEMAP_URL:
      PRERENDER_URL:
      PRERENDER_PROTOCOL:
    networks:
      traefik-net:
      metric-net:
      prerender-net:
    healthcheck:
      disable: ${HEALTHCHECK_DISABLE:-false}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}

        traefik.http.services.redmic-web.loadbalancer.server.port: 3050

        traefik.http.middlewares.redmic-web-error-5xx.errors.status: ${TRAEFIK_ERROR_5XX_STATUS:-500-599}
        traefik.http.middlewares.redmic-web-error-5xx.errors.service: ${TRAEFIK_ERROR_5XX_SERVICE:-static-pages}
        traefik.http.middlewares.redmic-web-error-5xx.errors.query: ${TRAEFIK_ERROR_5XX_QUERY:-/web-5xx/}

        traefik.http.routers.redmic-web.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.redmic-web.rule: Host(`${PUBLIC_HOSTNAME}`, `${ALT_TRAEFIK_DOMAIN_NAME}.${ALT_TRAEFIK_PRIMARY_TLD}`)
        traefik.http.routers.redmic-web.middlewares: redmic-web-error-5xx

        traefik.http.routers.ecomarcan-alt-tld.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.ecomarcan-alt-tld.rule: HostRegexp(`{s:[a-z]*\.?}${ALT_TRAEFIK_DOMAIN_NAME}.{tld:${ALT_TRAEFIK_SECONDARY_TLDS}}`)
        traefik.http.middlewares.ecomarcan-alt-tld-redirect.redirectregex.regex: ^(.+${ALT_TRAEFIK_DOMAIN_NAME}\.).*$$
        traefik.http.middlewares.ecomarcan-alt-tld-redirect.redirectregex.replacement: $${1}${ALT_TRAEFIK_PRIMARY_TLD}
        traefik.http.middlewares.ecomarcan-alt-tld-redirect.redirectregex.permanent: 'true'
        traefik.http.routers.ecomarcan-alt-tld.middlewares: ecomarcan-alt-tld-redirect
        traefik.http.routers.ecomarcan-alt-tld.service: noop@internal

        traefik.http.routers.redmic-web-es.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.redmic-web-es.rule: Host(`es.${PUBLIC_HOSTNAME}`, `es.${ALT_TRAEFIK_DOMAIN_NAME}.${ALT_TRAEFIK_PRIMARY_TLD}`)
        traefik.http.middlewares.redmic-web-es-regex.redirectregex.regex: ^(.*):\/\/\w+\.(.*)$$
        traefik.http.middlewares.redmic-web-es-regex.redirectregex.replacement: $${1}://$${2}
        traefik.http.middlewares.redmic-web-es-regex.redirectregex.permanent: 'true'
        traefik.http.routers.redmic-web-es.middlewares: redmic-web-es-regex
        traefik.http.routers.redmic-web-es.service: noop@internal

        traefik.http.routers.redmic-web-en.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.redmic-web-en.rule: Host(`en.${PUBLIC_HOSTNAME}`, `en.${ALT_TRAEFIK_DOMAIN_NAME}.${ALT_TRAEFIK_PRIMARY_TLD}`)
        traefik.http.middlewares.add-en-language-header.headers.customrequestheaders.content-language: en
        traefik.http.routers.redmic-web-en.middlewares: add-en-language-header, redmic-web-error-5xx
      restart_policy:
        delay: ${RESTART_DELAY:-1s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-2}'
          memory: ${RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-128M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  prerender-net:
    name: ${PRERENDER_NET_NAME:-prerender-net}
    driver: ${PRERENDER_NET_DRIVER:-overlay}
    external: true
