version: '3.5'

services:
  web:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - OAUTH_URL
      - OAUTH_CLIENT_SECRET
    networks:
      - traefik-net
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: '${PORT}'
        traefik.docker.network: traefik-net
        traefik.default.frontend.rule: Host:${PUBLIC_HOSTNAME}
        traefik.es.frontend.rule: Host:es.${PUBLIC_HOSTNAME}
        traefik.es.frontend.redirect.regex: ^(.*):\\/\\/es\\.(.*)$$
        traefik.es.frontend.redirect.replacement: $$1://$$2
        traefik.es.frontend.redirect.permanent: 'true'
        traefik.en.frontend.rule: Host:en.${PUBLIC_HOSTNAME}
        traefik.en.frontend.headers.customRequestHeaders: content-language:en
        traefik.backend: web
        traefik.frontend.errors.5xx.status: 500-599
        traefik.frontend.errors.5xx.backend: static-pages-static-pages-static-pages
        traefik.frontend.errors.5xx.query: '/web-5xx/'
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '2'
          memory: 128M
        reservations:
          memory: 103M

networks:
  traefik-net:
    external: true
