version: '3.5'

services:
  web:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      OAUTH_URL:
      OAUTH_CLIENT_SECRET:
      API_URL:
      PRODUCTION:
    networks:
      - traefik-net
      - metric-net
    healthcheck:
      test: wget --spider -q http://localhost:${PORT}
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.default.frontend.rule: Host:${PUBLIC_HOSTNAME}
        traefik.redirect.frontend.rule: HostRegexp:{subdomain:www|es}.${PUBLIC_HOSTNAME}
        traefik.redirect.frontend.redirect.regex: ^(.*):\\/\\/\\w+\\.(.*)$$
        traefik.redirect.frontend.redirect.replacement: $$1://$$2
        traefik.redirect.frontend.redirect.permanent: 'true'
        traefik.en.frontend.rule: Host:en.${PUBLIC_HOSTNAME}
        traefik.en.frontend.headers.customRequestHeaders: content-language:en
        traefik.frontend.errors.5xx.status: 500-599
        traefik.frontend.errors.5xx.backend: static-pages-static-pages-static-pages
        traefik.frontend.errors.5xx.query: '/web-5xx/'
        traefik.backend: web
        traefik.port: '${PORT}'
      restart_policy:
        delay: 10s
      update_config:
        delay: 10s
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.001'
          memory: 64M

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true
