version: '3.9'

services:
  web:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/client/web}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        NODE_IMAGE_TAG:
    environment:
      OAUTH_URL:
      OAUTH_CLIENT_SECRET:
      API_URL:
    networks:
      traefik-net:
      metric-net:
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.enable: 'true'

        traefik.http.services.redmic-web.loadbalancer.server.port: 3050
        traefik.http.services.redmic-web.loadbalancer.passhostheader: 'false'

        traefik.http.middlewares.redmic-web-error-5xx.errors.status: ${TRAEFIK_ERROR_5XX_STATUS:-500-599}
        traefik.http.middlewares.redmic-web-error-5xx.errors.service: ${TRAEFIK_ERROR_5XX_SERVICE:-static-pages}
        traefik.http.middlewares.redmic-web-error-5xx.errors.query: ${TRAEFIK_ERROR_5XX_QUERY:-/web-5xx/}

        traefik.http.routers.redmic-web.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.redmic-web.rule: Host(`${PUBLIC_HOSTNAME}`)
        traefik.http.routers.redmic-web.middlewares: redmic-web-error-5xx

        traefik.http.routers.redmic-web-es.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.redmic-web-es.rule: Host(`es.${PUBLIC_HOSTNAME}`)
        traefik.http.middlewares.redmic-web-es-regex.redirectregex.regex: ^(.*):\/\/\w+\.(.*)$$
        traefik.http.middlewares.redmic-web-es-regex.redirectregex.replacement: $${1}://$${2}
        traefik.http.middlewares.redmic-web-es-regex.redirectregex.permanent: 'true'
        traefik.http.routers.redmic-web-es.middlewares: redmic-web-es-regex
        traefik.http.routers.redmic-web-es.service: noop@internal

        traefik.http.routers.redmic-web-en.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.redmic-web-en.rule: Host(`en.${PUBLIC_HOSTNAME}`)
        traefik.http.middlewares.add-en-language-header.headers.customrequestheaders.content-language: en
        traefik.http.routers.redmic-web-en.middlewares: add-en-language-header, redmic-web-error-5xx
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true
