version: '3.5'

services:
  web:
    ports:
      - target: ${WEB_PORT}
        published: ${WEB_PORT}
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${WEB_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: PathPrefix:/
        traefik.backend: web
        traefik.frontend.errors.5xx.status: "500-599"
        traefik.frontend.errors.5xx.backend: static-pages-static-pages-static-pages
        traefik.frontend.errors.5xx.query: '/web-5xx/'
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '2'
          memory: 128M
        reservations:
          memory: 103M
